name = "Create Arcane Engineering"
author = "FortnitePro420Xx"
version = "1.9.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "83089084a83bb1716edc42b26ca49c4db530590acd1308bea39623425be36ea4"

[versions]
forge = "40.2.17"
minecraft = "1.18.2"
