name = "Create Arcane Engineering"
author = "FortnitePro420Xx"
version = "0.1.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7fddc78c417b78ca0514a489e84974f2b5531238e9482075b96c71903a93c412"

[versions]
forge = "40.2.17"
minecraft = "1.18.2"
