name = "Create Arcane Engineering"
author = "FortnitePro420Xx"
version = "0.1.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fda7711dcba4785723576dbfe404a6e4bb6f13b02d4833e7e6363774b39df1ba"

[versions]
forge = "40.2.17"
minecraft = "1.18.2"
