name = "Create Arcane Engineering"
author = "FortnitePro420Xx"
version = "0.1.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9aecf9821874117c49690bd9c3283b5eceebdce602c816a2d372f67551681b36"

[versions]
forge = "40.2.17"
minecraft = "1.18.2"
