name = "Create Arcane Engineering"
author = "FortnitePro420Xx"
version = "0.1.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac6f6ef239290f12761c55f49b97c7427926949279fa1d99f8945a5204d9fd94"

[versions]
forge = "40.2.17"
minecraft = "1.18.2"
