name = "Create Arcane Engineering"
author = "FortnitePro420Xx"
version = "0.1.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e164bd14b94ddea78b2d020dc015e1b355b1df375a1e371e5a79e4a9ac7f84a0"

[versions]
forge = "40.2.17"
minecraft = "1.18.2"
