name = "Create Arcane Engineering"
author = "FortnitePro420Xx"
version = "0.1.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43e8e2f461d09d1a41953736bf4e27318eae2e33ea0309793f0ac10b7dd6f129"

[versions]
forge = "40.2.17"
minecraft = "1.18.2"
