name = "Create Arcane Engineering"
author = "FortnitePro420Xx"
version = "0.1.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d70666a93033fcaa0b8526a853b82d4d52f179b981779828a350c4409ed3c1d"

[versions]
forge = "40.2.17"
minecraft = "1.18.2"
