name = "Create Arcane Engineering"
author = "FortnitePro420Xx"
version = "0.1.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "091b875901496227940a96730e19dc19a0ecaa5884dd3836e72c18b7b9d133f4"

[versions]
forge = "40.2.17"
minecraft = "1.18.2"
