name = "Create Arcane Engineering"
author = "FortnitePro420Xx"
version = "0.1.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "204094bf04bf5b67d201c02540f359a0dd2a629224363bf4e608e9bb62c16441"

[versions]
forge = "40.2.17"
minecraft = "1.18.2"
