name = "Create Arcane Engineering"
author = "FortnitePro420Xx"
version = "0.1.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "465b2dc8fdaa68100aadcec918d59ab2f1333cba1bb04fe77a6adfc88d83a386"

[versions]
forge = "40.2.9"
minecraft = "1.18.2"
