name = "Create Arcane Engineering"
author = "FortnitePro420Xx"
version = "0.1.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d890bda43ab7d0716bbde75423148298799ab28468ff5c596096c2e56e5f894"

[versions]
forge = "40.2.17"
minecraft = "1.18.2"
