name = "Create Arcane Engineering"
author = "FortnitePro420Xx"
version = "0.1.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a77eaaa81f63c0f5048ae0cca6e5870b37daf8c1c2132cdade269dbd1d5850d7"

[versions]
forge = "40.2.17"
minecraft = "1.18.2"
