name = "Create Arcane Engineering"
author = "FortnitePro420Xx"
version = "0.1.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d516fdd58a9d5143004d2a1ebf402d2c667ed6ef02da080ddbf1feca040e0fa"

[versions]
forge = "40.2.17"
minecraft = "1.18.2"
