name = "Create Arcane Engineering"
author = "FortnitePro420Xx"
version = "0.1.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d839357f3037a296ca01f45e134bb05b5c28fbb3600c6d58c6f228df0fec7ee"

[versions]
forge = "40.2.17"
minecraft = "1.18.2"
